feat: add rm support to strigify and uglify-js as package dependencies
MikeMcl/big.js pull request #144
Opened 2020-08-24 03:09 UTC by nutboltu

2020-08-26 13:20 UTC, nutboltu commented
@MikeMcl would you please take a look? I will add unit tests after getting an initial review from you.

2020-08-27 17:23 UTC, MikeMcl requested changes
I was about to reply this very evening anyway. Honest!

I've actually already done this work - the code part anyway - but, as usual, one change leads to another, and I have a bit more refactoring to do before pushing.

I'll take this PR from you anyway, though, as it includes other stuff. When I publish, I will probably remove the minified version and all that goes with it.

Thanks for your good work.

2020-08-27 17:23 UTC, MikeMcl commented on big.js
> +      if (x.c.length > ++k) round(x, n, rm || Big.RM);
Needs to be 
```js
if (x.c.length > ++k) round(x, n, rm === UNDEFINED ? Big.RM : rm);
```
as `rm` may be `0`.

2020-08-28 04:34 UTC, nutboltu commented
@MikeMcl no worries. Thanks for your time to review. Feel free to take my changes. Whenever you are done with the changes, I'll close the PR.
However, if you want me PR to get merge first and then you'll start working on top of it, that would be another option. Let me know which works for you.

2020-08-28 04:43 UTC, nutboltu commented on big.js
> +      if (x.c.length > ++k) round(x, n, rm || Big.RM);
fixed.

2020-09-07 22:10 UTC, merged